### ISSUE TITLE
Server's title won't disappear

### ISSUE THREAD

**Issue by egozi44** [puckzxz/NotAnotherAnimeTheme#111] opened 2019-04-03 02:34 UTC
So after one of the few recent discord updates, I start getting this annoying bug, it won't happen if the theme is turn off

![hgfhfg](https://user-images.githubusercontent.com/14190834/55448936-5a6b8600-55d2-11e9-901b-63edcdb83644.PNG)

Does anyone know how to fix it?

**Comment by Qu4k3** [comment] 2019-04-08 18:09
Hi @egozi44, sorry for the delay.

Are you still experiencing this bug ? Or restarting your client has fixed it ?

Let us know, so we can get a closer look on it or close this issue.
We can offer a better support directly from our support discord server - https://discord.gg/FdZhbjY

Thank you

**Comment by egozi44** [comment] 2019-04-09 01:04
Yup still have it, not sure if it something from my end cause I tried turn off all of the plugins, and saw it's still there unless I turn off the theme

**Comment by puckzxz** [comment] 2019-04-09 02:20
I have been trying to recreate this issue on my end and I can't do it.  Have you made any other modifications to the theme or your client?  Are you running the Stable, PTB, or Canary version of the Discord client?  If you've made any other modifications could you upload your theme file here so I can test it locally.  Just to start narrowing things down, do you have hardware acceleration enabled?

**Comment by egozi44** [comment] 2019-04-09 02:28
After further testings I think the issue is really being caused by some plugin (DetailedServerTooltips in this case)

I will let you know if this is the case after a bit more testing, thx

**Comment by puckzxz** [comment] 2019-04-17 00:51
I'm gonna close this issue, if the issue is still occurring feel free to open another one.

**Closed by puckzxz** 2019-04-17 00:51 UTC
