### ISSUE TITLE
Background is not themed

### ISSUE THREAD

**Issue by 3Golden3** [puckzxz/NotAnotherAnimeTheme#139] opened 2019-09-21 02:34 UTC
This theme was working just fine yesterday but when i logged on today, lo and behold, this happened: https://imgur.com/ivbxAR7 . I wanted to make sure this issue was known

**Comment by ItzSnowXD** [comment] 2019-09-21 02:38
Yep, the issue is already known. The dev/designer is fixing it tonight.

**Comment by ashergz** [comment] 2019-09-21 02:59
Thank you for the update.

**Comment by puckzxz** [comment] 2019-09-21 05:20
Fixed in this commit https://github.com/puckzxz/NotAnotherAnimeTheme/commit/1252acb3abfa7b4059ca9e196c9b476209e05041

Thank you for your patience.

**Closed by puckzxz** 2019-09-21 05:20 UTC
